# Generated by Django 5.1.7 on 2025-04-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_userauth_name'), ('api', '0004_merge'), ('api', '0005_dorm_room_student_studentbooking'), ('api', '0006_room_current_occupants_studentbooking_confirmed'), ('api', '0007_studentinfo'), ('api', '0008_maintenancerequest'), ('api', '0009_userauth_is_admin'), ('api', '0010_remove_studentbooking_created_at_and_more'), ('api', '0011_studentbooking_status'), ('api', '0012_maintenancerequest_status')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('salt', models.CharField(max_length=32)),
                ('hashed_password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='DefaultUsername', max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('dorm_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='DefaultUsername', max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='api.userauth')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_AC', models.BooleanField(default=False)),
                ('has_private_bath', models.BooleanField(default=False)),
                ('cost_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.dorm')),
                ('current_occupants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='api.userauth')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='studentBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('lease_length', models.IntegerField()),
                ('dorm_name', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=50)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userauth')),
                ('confirmed', models.BooleanField(blank=True, default=None, null=True)),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=25)),
                ('issue', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=1000)),
                ('priority', models.CharField(max_length=50)),
                ('date_created', models.CharField(max_length=50)),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
