# Generated by Django 5.1.7 on 2025-03-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='name',
            field=models.CharField(default='DefaultUsername', max_length=255),
        ),
    ]
