# Generated by Django 5.1.7 on 2025-04-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dorm_room_student_studentbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_occupants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentbooking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
