# Generated by Django 5.1.7 on 2025-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=25)),
                ('issue', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=1000)),
                ('priority', models.CharField(max_length=50)),
                ('date_created', models.CharField(max_length=50)),
            ],
        ),
    ]
