# Generated by Django 5.0.13 on 2025-04-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
