# Generated by Django 5.1.7 on 2025-04-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
