# Generated by Django 5.0.13 on 2025-04-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userauth_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
