# Generated by Django 5.1.7 on 2025-04-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_studentbooking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbooking',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
