# Generated by Django 5.1.7 on 2025-04-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_studentbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
